import Head from 'next/head'

import {Header} from '../components/Header/Header.jsx'

import styles from '../assets/styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dupe.dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Junior Gate!
        </h1>
        <h2 className="cursive">
          This is Quentin font
        </h2>
      </main>
    </div>
  )
}
